# Generated by Django 4.2.14 on 2024-07-30 14:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.URLField(max_length=100)),
                ('url', models.URLField()),
                ('fecha_carga', models.DateField(auto_now=True)),
            ],
        ),
    ]
